services:
  db:
    image: mysql:8
    container_name: toolbox-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME:-toolbox_db}
      MYSQL_USER: ${DB_USER:-toolbox_user}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - site_data:/var/lib/mysql

  main:
    build: .
    container_name: toolbox-io
    restart: always
    depends_on:
      - db
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: toolbox_db
      DB_USER: toolbox_user
      DB_PASSWORD: ${DB_PASSWORD}
      DEBUG: ${DEBUG:-false}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /root/site/frontend
          ignore:
            - node_modules/
        - action: sync+restart
          path: ./backend/main
          target: /root/site/backend
        - action: rebuild
          path: ./backend/requirements.txt
        - action: rebuild
          path: ./frontend/package.json

  vite:
    build:
      dockerfile: frontend/vite/Dockerfile
      context: .
    container_name: vite
    restart: always
    ports:
      - "8002:8002"
    profiles:
      - "dev"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /root/site/frontend
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

  download:
    build:
      context: .
      dockerfile: backend/download/Dockerfile
    container_name: toolbox-io-download
    restart: always
    ports:
      - "8001:8001"
    develop:
      watch:
        - action: sync+restart
          path: ./backend/download
          target: /root/site/backend/download
        - action: rebuild
          path: ./backend/requirements.txt
        - action: rebuild
          path: ./frontend/package.json
    volumes:
      - site_download_cache:/root/site/backend/download/cache
    environment:
      SMTP_PASSWORD: ${SMTP_PASSWORD}

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: toolbox-caddy
    restart: always
    profiles: ["prod"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - site_certs:/root/site/certs
    environment:
      XDG_DATA_HOME: /root/site/certs
      XDG_CONFIG_HOME: /root/site/certs

volumes:
  site_data:
    name: toolbox-io_site_data
  site_certs:
  site_download_cache: